- hosts: terraform
  tasks:
  - name: Python3 and virtualenv install
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: dependencies install with pip (django and django rest)
    pip:
      virtualenv: /home/ubuntu/thiago/venv
      name:
        - django
        - djangorestframework