- hosts: terraform
  tasks:
  - name: Python3 and virtualenv install
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: dependencies install with pip in a virutal env (django and django rest)
    pip:
      virtualenv: /home/ubuntu/thiago/venv
      name:
        - django
        - djangorestframework
  - name: project init
    shell: '. /home/ubuntu/thiago/venv/bin/activate; django-admin startproject app /home/ubuntu/thiago'