- hosts: terraform
  tasks:
  - name: criar arquivo
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Testando o ansible, hehe</h1>

  - name: Criar servidor
    shell: "nohup busybox httpd -f -p 8080 &"